<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <StartupObject>DSA.DataStructures.String.ValidParanthesis</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="LeetcodeProblems\Arrays\Patterns\Sliding Window\Variable\" />
    <Folder Include="LeetcodeProblems\NewFolder\" />
    <Folder Include="LeetcodeProblems\Random\" />
  </ItemGroup>

</Project>
